name: hamon_task
description: "hamon task"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  http: ^1.1.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  provider: ^6.1.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  integration_test:
    sdk: flutter
  mocktail: ^1.0.1
  injectable_generator: ^2.4.0

flutter:

  uses-material-design: true


  assets:
    - assets/classroom.png
    - assets/students.png
    - assets/teacher.png